### PR TITLE
docs: update docs and examples for file-storage, add troubleshooting guide

### LINKED ISSUE #46: docs: update file-storage documentation
Now that AWS SDK has been updated to v3, the README examples should be updated to include the changes, specifically `packages/file-storage/README.md`. It should document the breaking change that `accessKeyId` and `secretAccessKey` should be passed in a `credentials` object, `s3BucketEndpoint` is no longer supported, and `endpoint` has been replaced by `region`. Document that `endpoint` can currently be passed in and the region will be extracted, but `region` should be preferred.

### PR DESCRIPTION
**Pull request by eamon0989**
# Description

Updates documentation and examples for `file-storage`
Adds a troubleshooting guide

Fixes #46 

## Type of change

Please delete options that are not relevant.

- [x] Documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by getlarge — DISMISSED** [review]

**Comment by getlarge** [comment]
@eamon0989 for some reason the tests are not passing for FileStorageS3, i triggered the tests a second time and the same error occurred. This is maybe a bit more than flakiness.
Can you please try to fix it ?

**Comment by eamon0989** [comment]
> @eamon0989 for some reason the tests are not passing for FileStorageS3, i triggered the tests a second time and the same error occurred. This is maybe a bit more than flakiness. Can you please try to fix it ?

That's strange, as this is just a documentation change. I'll take a look 👍🏼

**Comment by getlarge** [comment]
> > @eamon0989 for some reason the tests are not passing for FileStorageS3, i triggered the tests a second time and the same error occurred. This is maybe a bit more than flakiness. Can you please try to fix it ?
> 
> That's strange, as this is just a documentation change. I'll take a look 👍🏼

Those tests were already a bit flaky when you made the migration to AWS SDK v3 but acceptable.
Now 2 failures out of 2 trials is a bit … meeh
Maybe the AWS SDK version was not pinned and something changed in the meantime ?

**Comment by eamon0989** [comment]
> 



> > > @eamon0989 for some reason the tests are not passing for FileStorageS3, i triggered the tests a second time and the same error occurred. This is maybe a bit more than flakiness. Can you please try to fix it ?
> > 
> > 
> > That's strange, as this is just a documentation change. I'll take a look 👍🏼
> 
> Those tests were already a bit flaky when you made the migration to AWS SDK v3 but acceptable. Now 2 failures out of 2 trials is a bit … meeh Maybe the AWS SDK version was not pinned and something changed in the meantime ?

Nice catch, the dependencies weren't pinned and there have been 3 versions released in the last 3 days. I've pinned them, hopefully that will fix the problem.

**Review by getlarge — APPROVED** [review]

**Pull request merged**
